
    //======================================
    // DO NOT EDIT THIS FILE
    //======================================
    // This file is dynamically modified to match OS environment variables.
    // All the magic is done in `additional-build-steps.js`. Go there for details.
    export const environment = {
      production: "false",
      TASTYTERM_OAUTH_CLIENT_ID: "l33tpr0gr4m3r-fd0b-408a-bbb9-4224d8451e69"
    };
  