
    //======================================
    // DO NOT EDIT THIS FILE
    //======================================
    // This file is dynamically generated to match OS environment variables.
    // All the magic is done in `additional-build-steps.js`. Go there for details.
    export const environment = {
      production: "false",
      TASTYTERM_OAUTH_CLIENT_ID: "undefined"
    };
  